version: '3.8'
services:
  backend:
    build: 
      context: ./server
    env_file:
      - ./.env
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./server:/app
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}


  frontend:
    build: ./client
    ports:
      - "3000:80"
    
  db:
    image: mysql:8
    restart: always  
    env_file:
      - ./.env  # Ensure this path is correct
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
volumes:
  db_data:
