version: '3.8'
services:
  db:
    image: mysql:5.7  # Use a compatible version
    restart: always  
    env_file:
      - ./.env 
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - app-network
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
  backend:
    build: 
      context: ./server
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./server:/app
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    networks:
      - app-network

  frontend:
    build: ./client
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "8080:80"
    
volumes:
  db_data:

networks:
  app-network:
